export const NOTIFY_USER = 'NOTIFY_USER';
export const DISABLE_BALANCE_ADD = 'DISABLE_BALANCE_ADD';
export const DISABLE_BALANCE_EDIT = 'DISABLE_BALANCE_EDIT';
export const ALLOW_REGISTER = 'ALLOW_REGISTER';
